Nifty50 = {'ADANIPORTS':['adani ports', 'adaniports'],
            'ASIANPAINT':['asaian paint', 'asaianpaint'],
            'AXISBANK':['axis bank', 'axisbank'],
            'BAJAJ-AUTO':['bajaj-auto' 'bajaj auto'],
            'BAJFINANCE':['bajaj fin', 'bajfinance'],
            'BAJAJFINSV':['bajaj finsv', 'bajajfinsv'],
            'BPCL':['bpcl'],
            'BHARTIARTL':['bharti airtel', 'airtel'],
            'INFRATEL':['infratel'],
            'CIPLA':['cipla'],
            'COALINDIA':['coal india', 'coalindia'],
            'DRREDDY':['drreddy', "dr reddy"],
            'EICHERMOT':['eicher', 'eicher motors'],
            'GAIL':['gail'],
            'GRASIM':['grasim'],
            'HCLTECH':['hcl tech', 'hcl'],
            'HDFCBANK':['hdfc bank', 'hdfcbank'],
            'HEROMOTOCO':['hero', 'hero motorcorp'],
            'HINDALCO':['hindalco'],
            'HINDPETRO':['hindpetro'],
            'HINDUNILVR':['hul', 'hindunilvr'],
            'HDFC':['hdfc'],
            'ITC':['itc'],
            'ICICIBANK':['icici'],
            'IBULHSGFIN':['ibulhsgfin'],
            'IOC':['ioc', 'indian oil'],
            'INDUSINDBK':['indusindbk', 'indusind'],
            'INFY':['infosys', 'infy', 'infosi'],
            'JSWSTEEL':['jswsteel', 'jsw steel', 'jsw steels'],
            'KOTAKBANK':['kotakbank', 'kotak mahindra'],
            'LT':['larsen'],
            'M&M':[],
            'MARUTI':['maruti'],
            'NTPC':[],
            'ONGC':[],
            'POWERGRID':[],
            'RELIANCE':['relianc'],
            'SBIN':[],
            'SUNPHARMA':[],
            'TCS':['tcs', 'tata consultancy'],
            'TATAMOTORS':[],
            'TATASTEEL':['tata steel'],
            'TECHM':[],
            'TITAN':['titan'],
            'UPL':['upl'],
            'ULTRACEMCO':['ultra cement'],
            'VEDL':['vedenta', 'vedl'],
            'WIPRO':['wipro'],
            'YESBANK':['ye', 'ye bank', 'yes bank'],
            'ZEEL':[]}


def get_all_stocks_possible_names():
    possible_names = []
    for stock, possible_name in Nifty50.items():
        for name in possible_name:
            possible_names.append(name)
    return possible_names

# print(get_all_stocks_possible_names())