Nifty50 = {'ADANIPORTS':['adaniports', 'adani ports'],
            'ASIANPAINT':['asaianpaint', 'asaian paint'],
            'AXISBANK':['axisbank', 'axis bank'],
            'BAJAJ-AUTO':['bajaj-auto' 'bajaj auto'],
            'BAJFINANCE':['bajfinance'],
            'BAJAJFINSV':['bajajfinsv', 'bajaj finsv'],
            'BPCL':['bpcl'],
            'BHARTIARTL':['bharti aitel', 'airtel'],
            'INFRATEL':['infratel'],
            'CIPLA':['cipla'],
            'COALINDIA':['coal india', 'coalindia'],
            'DRREDDY':['drreddy', "dr reddy"],
            'EICHERMOT':['eicher', 'eicher motors'],
            'GAIL':['gail'],
            'GRASIM':['grasim'],
            'HCLTECH':['hcltech', 'hcl'],
            'HDFCBANK':['hdfcbank', 'hdfc bank'],
            'HEROMOTOCO':['hero', 'hero motorcorp'],
            'HINDALCO':['hindalco'],
            'HINDPETRO':['hindpetro'],
            'HINDUNILVR':['hul', 'hindunilvr'],
            'HDFC':['hdfc'],
            'ITC':['itc'],
            'ICICIBANK':['icici'],
            'IBULHSGFIN':['ibulhsgfin'],
            'IOC':['ioc', 'indian oil'],
            'INDUSINDBK':['indusindbk', 'indusind'],
            'INFY':['infosys', 'infy', 'infosi'],
            'JSWSTEEL':['jswsteel', 'jsw steel', 'jsw steels'],
            'KOTAKBANK':['kotakbank', 'kotak mahindra'],
            'LT':['larsen'],
            'M&M':[],
            'MARUTI':['maruti'],
            'NTPC':[],
            'ONGC':[],
            'POWERGRID':[],
            'RELIANCE':['relianc'],
            'SBIN':[],
            'SUNPHARMA':[],
            'TCS':['tcs', 'tata consultancy'],
            'TATAMOTORS':[],
            'TATASTEEL':['tata steel'],
            'TECHM':[],
            'TITAN':['titan'],
            'UPL':['upl'],
            'ULTRACEMCO':['ultra cement'],
            'VEDL':['vedenta', 'vedl'],
            'WIPRO':['wipro'],
            'YESBANK':['ye', 'ye bank', 'yes bank'],
            'ZEEL':[]}